kicad: use python 3.12
This reverts commit 6cec87c32d0dabb868da784734192c651d1db9df.

Now that https://github.com/NixOS/nixpkgs/pull/326142 has landed,
there's no reason to keep ourselves pinned to Python 3.11 anymore.

As a happy side effect, this also fixes a bug with
6cec87c32d0dabb868da784734192c651d1db9df which broke our ability to use
kicad addons:

    $ nix build --impure --expr 'with import ./. {}; pkgs.kicad.override { addons = with pkgs.kicadAddons; [kikit kikit-library]; }' -L
    ...
    error:
           … while calling the 'derivationStrict' builtin
             at <nix/derivation-internal.nix>:34:12:
               33|
               34|   strict = derivationStrict drvAttrs;
                 |            ^
               35|

           … while evaluating derivation 'kicad-8.0.4'
             whose name attribute is located at /home/jeremy/src/github.com/NixOS/nixpkgs-alt/pkgs/stdenv/generic/make-derivation.nix:336:7

           … while evaluating attribute 'makeWrapperArgs' of derivation 'kicad-8.0.4'
             at /home/jeremy/src/github.com/NixOS/nixpkgs-alt/pkgs/applications/science/electronics/kicad/default.nix:201:3:
              200|   # We are emulating wrapGAppsHook3, along with other variables to the wrapper
              201|   makeWrapperArgs = with passthru.libraries; [
                 |   ^
              202|     "--prefix XDG_DATA_DIRS : ${base}/share"

           (stack trace truncated; use '--show-trace' to show the full, detailed trace)

           error: function 'anonymous lambda' called with unexpected argument 'python'
           at /home/jeremy/src/github.com/NixOS/nixpkgs-alt/pkgs/applications/science/electronics/kicad/addons/kikit.nix:2:1:
                1| # For building the multiple addons that are in the kikit repo.
                2| { stdenv
                 | ^
                3| , bc
           Did you mean python3?